from enum import Enum
from typing import Set

class KYCState(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    PROFILE_INCOMPLETE = "PROFILE_INCOMPLETE"
    READY_FOR_VERIFICATION = "READY_FOR_VERIFICATION"
    VERIFICATION_STARTED = "VERIFICATION_STARTED"
    DOCUMENT_REQUIRED = "DOCUMENT_REQUIRED"
    DOCUMENT_SUBMITTED = "DOCUMENT_SUBMITTED"
    LIVENESS_REQUIRED = "LIVENESS_REQUIRED"
    LIVENESS_SUBMITTED = "LIVENESS_SUBMITTED"
    SCREENING_IN_PROGRESS = "SCREENING_IN_PROGRESS"
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    MORE_INFORMATION_REQUIRED = "MORE_INFORMATION_REQUIRED"
    RETRY_REQUIRED = "RETRY_REQUIRED"

VALID_KYC_TRANSITIONS = {
    KYCState.NOT_STARTED: {KYCState.PROFILE_INCOMPLETE, KYCState.READY_FOR_VERIFICATION},
    KYCState.PROFILE_INCOMPLETE: {KYCState.READY_FOR_VERIFICATION},
    KYCState.READY_FOR_VERIFICATION: {KYCState.VERIFICATION_STARTED, KYCState.DOCUMENT_REQUIRED},
    KYCState.VERIFICATION_STARTED: {KYCState.DOCUMENT_REQUIRED, KYCState.DOCUMENT_SUBMITTED},
    KYCState.DOCUMENT_REQUIRED: {KYCState.DOCUMENT_SUBMITTED, KYCState.RETRY_REQUIRED},
    KYCState.DOCUMENT_SUBMITTED: {KYCState.LIVENESS_REQUIRED, KYCState.SCREENING_IN_PROGRESS},
    KYCState.LIVENESS_REQUIRED: {KYCState.LIVENESS_SUBMITTED, KYCState.RETRY_REQUIRED},
    KYCState.LIVENESS_SUBMITTED: {KYCState.SCREENING_IN_PROGRESS},
    KYCState.SCREENING_IN_PROGRESS: {KYCState.APPROVED, KYCState.PENDING_REVIEW, KYCState.REJECTED, KYCState.MORE_INFORMATION_REQUIRED},
    KYCState.PENDING_REVIEW: {KYCState.APPROVED, KYCState.REJECTED, KYCState.MORE_INFORMATION_REQUIRED},
    KYCState.MORE_INFORMATION_REQUIRED: {KYCState.DOCUMENT_SUBMITTED, KYCState.LIVENESS_SUBMITTED},
    KYCState.RETRY_REQUIRED: {KYCState.DOCUMENT_SUBMITTED},
    KYCState.APPROVED: set(),
    KYCState.REJECTED: set()
}

class KYCStateMachine:
    @staticmethod
    def transition(current: KYCState, target: KYCState) -> KYCState:
        allowed = VALID_KYC_TRANSITIONS.get(current, set())
        if target not in allowed:
            raise ValueError(f"Illegal KYC state transition from {current} to {target}")
        return target
